name: CaptureTheFlag
main: net.novauniverse.capturetheflag.NovaCaptureTheFlag
description: A minigame by novauniverse
version: 1.0.0
api-version: 1.13

depend: [NovaCore, NovaCoreGameEngine]
softdepend: [NovaGamesTarget]

authors: [Zeeraa, NovaUniverse]